# Generated by Django 3.0.8 on 2020-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('ph_no', models.IntegerField(max_length=12)),
                ('email_address', models.TextField(max_length=200)),
                ('company_name', models.TextField(max_length=150)),
                ('GST_no', models.TextField(max_length=25)),
                ('Address', models.TextField(max_length=250)),
                ('city', models.TextField(max_length=50)),
                ('State', models.TextField(max_length=100)),
                ('pincode', models.IntegerField(max_length=10)),
            ],
        ),
    ]
