# Generated by Django 3.0.8 on 2020-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptev', '0003_auto_20200819_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ph_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
